from pathlib import Path
from typing import List
from contextvault.core.models import Citation
from contextvault.core.exceptions import ContextVaultError

class FileWriter:
    def write_markdown(self, content: str, path: Path, title: str, sources: List[Citation]) -> Path:
        header = f"# {title}\n\n_Generated by Context Vault_\n\n"
        
        sources_text = ""
        if sources:
            sources_text = "\n\n## Sources\n"
            for i, s in enumerate(sources, 1):
                loc = []
                if s.page:
                    loc.append(f"page {s.page}")
                if s.section or s.heading:
                    loc.append(s.heading or s.section or "")
                loc_str = f" ({', '.join(loc)})" if loc else ""
                sources_text += f"- [{i}] {s.file_path}{loc_str}\n"
            
        full_content = header + content + sources_text
        return self.safe_write(full_content, path)
        
    def safe_write(self, content: str, path: Path) -> Path:
        if path.exists():
            raise ContextVaultError(f"Path already exists: {path}. Overwrite is strictly forbidden.")
            
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)
            
        return path
